version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: mi_nginx
    ports:
      - '8080:80'  # Mapea el puerto 8080 de tu máquina al puerto 80 del contenedor
    volumes:
      - './src:/usr/share/nginx/html'  # Mapea el directorio src a la ruta del contenedor
    restart: always
